language: cpp
compiler: gcc
branches:
  only:
  - master
  - built-test

sudo: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  # Combine global build options with OS/compiler-dependent options
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
  
  
    
install:
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  - pip install --user cpp-coveralls

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

script:
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DBUILD_TESTING=ON  -DCMAKE_CXX_FLAGS=-pg -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg  ../
  - make
  #- wget -O Toy_Data.zip https://www.dropbox.com/s/p94isegg18z3wuo/Toy_Data.zip?dl=1
  #- unzip Toy_Data.zip
  #- ../bin/PRSice --base TOY_BASE_GWAS.assoc --target TOY_TARGET_DATA --gtf Homo_sapiens.GRCh38.86.gtf.gz --msigdb c2.all.v6.2.symbols.gmt --set-perm 100
  #- gprof ../bin/PRSice > gprof.log
  - wget -O Test.zip https://www.dropbox.com/s/zuae45ybs96d2uk/Test.zip?dl=1
  - unzip -o Test.zip
  - ../bin/runUnitTests .
  #- head gprof.log -n 100
  #- ../test/runCoverage.sh . ../bin/runUnitTests ../test/data
  - cd ../
  - coveralls --build-root build --gcov-options '\-lp' -e test -e lib -e build/googletest-src -e build/CMakeFiles 
